source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'lowres_Example', :exclusive => true do
  pod "lowres", :path => "../"
end

target 'lowres_Tests', :exclusive => true do
  pod "lowres", :path => "../"
end
